# Generated by Django 5.2.11 on 2026-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_follow_alter_about_us_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='github',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='website',
        ),
        migrations.AddField(
            model_name='follow',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('email', 'Email'), ('website', 'Website')], default='facebook', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='url',
            field=models.URLField(default='Facebook'),
            preserve_default=False,
        ),
    ]
